# Generated by Django 3.0 on 2019-12-15 09:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='username')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='phone_number')),
                ('is_admin', models.BooleanField(max_length=6, verbose_name='staff_status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30, verbose_name='description')),
                ('house_name', models.CharField(max_length=60, verbose_name='house_name')),
                ('house_pic', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('price', models.CharField(max_length=60, verbose_name='price')),
                ('isFurnished', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50, verbose_name='furnished')),
                ('isParkingSpace', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=70, verbose_name='parkingspace')),
                ('isAvailable', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, verbose_name='available')),
                ('isFenced', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, verbose_name='fenced')),
                ('isHaveWater', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, verbose_name='water')),
                ('isNewHouse', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=80, verbose_name='new')),
                ('isNegotiable', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=80, verbose_name='new')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findr.User')),
            ],
        ),
    ]
