# Generated by Django 3.0 on 2020-01-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=160, null=True, unique=True, verbose_name='email'),
        ),
    ]
