# Generated by Django 3.0 on 2019-12-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='house',
            name='title',
            field=models.TextField(),
        ),
    ]
