# Generated by Django 3.0 on 2019-12-27 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findr', '0002_auto_20191227_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
