# Generated by Django 3.0 on 2020-01-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findr', '0004_auto_20191228_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='isNegotiable',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=80, verbose_name='Negotiable'),
        ),
    ]
