# Generated by Django 3.0 on 2019-12-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findr', '0004_auto_20191216_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='house_address',
            field=models.CharField(max_length=10000, null=True, verbose_name='house_address'),
        ),
    ]
