# Generated by Django 3.0 on 2019-12-17 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findr', '0005_apartment_house_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='apartment_categories',
        ),
        migrations.DeleteModel(
            name='ApartmentCategory',
        ),
    ]
