# Generated by Django 3.0 on 2019-12-19 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findr', '0006_auto_20191217_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
