# Generated by Django 3.0 on 2019-12-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findr', '0007_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=60, null=True, verbose_name='username'),
        ),
    ]
