# Generated by Django 3.0 on 2019-12-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findr', '0008_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='house_address',
            field=models.CharField(max_length=10000, verbose_name='house_address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=9, unique=True, verbose_name='phone_number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=60, verbose_name='username'),
        ),
    ]
