# Generated by Django 3.0 on 2019-12-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findr', '0009_auto_20191221_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, verbose_name='phone_number'),
        ),
    ]
